AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: service.handler
      Runtime: python3.6
      CodeUri: service.zip
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: post
